### ISSUE TITLE
Create issues to track progress

### ISSUE THREAD

**Issue by yungyuc** [ntut-xuan/PolygonDust#2]
@ntut-xuan , I wonder if you can reorganize the working items in [your schedule](https://github.com/yungyuc/nsdhw_24au/blob/ed6f48bf0412b8a5f9324cd055c49a4906700e8c/project/ntut-xuan/README.rst?plain=1#L110) into issues in this repository?  That will turn the items into a trackable format.  You will know more about your progress and efforts spent

**Comment by c1ydehhx** [comment]
No problem. I'll work on it.

**Comment by yungyuc** [comment]
Any progress on creating the issues?

**Comment by c1ydehhx** [comment]
Hi @yungyuc, thanks for tracking this issue.

I already create the issue that shows the task before v1.0.0. Any suggestion will be glad for me.

**Comment by yungyuc** [comment]
LGTM.  Please tag me if you have specific questions.
